### ISSUE TITLE
Assertion error while cogent reconstruct

### ISSUE THREAD

**Issue by fantastycrane** [Magdoll/Cogent#24] opened 2018-03-23 09:46 UTC
Hi, @Magdoll 

I ran into following error while running cogent reconstruction.

 """
Traceback (most recent call last):
  File "/share/nas1/liyingying/tools/soft/cogent/Anaconda/anaconda3/envs/anaCogent/bin/reconstruct_contig.py", line 4, in <module>
    __import__('pkg_resources').run_script('Cogent==2.1', 'reconstruct_contig.py')
  File "/share/nas1/liyingying/tools/soft/cogent/Anaconda/anaconda3/envs/anaCogent/lib/python2.7/site-packages/pkg_resources/__init__.py", line 750, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/share/nas1/liyingying/tools/soft/cogent/Anaconda/anaconda3/envs/anaCogent/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1527, in run_script
    exec(code, namespace, namespace)
  File "/share/nas1/liyingying/tools/soft/cogent/Anaconda/anaconda3/envs/anaCogent/lib/python2.7/site-packages/Cogent-2.1-py2.7.egg/EGG-INFO/scripts/reconstruct_contig.py", line 352, in <module>
    main()
  File "/share/nas1/liyingying/tools/soft/cogent/Anaconda/anaconda3/envs/anaCogent/lib/python2.7/site-packages/Cogent-2.1-py2.7.egg/EGG-INFO/scripts/reconstruct_contig.py", line 268, in main
    run_Cogent_on_split_files(dirs, depth=0)
  File "/share/nas1/liyingying/tools/soft/cogent/Anaconda/anaconda3/envs/anaCogent/lib/python2.7/site-packages/Cogent-2.1-py2.7.egg/EGG-INFO/scripts/reconstruct_contig.py", line 71, in run_Cogent_on_split_files
    run_Cogent_on_input()
  File "/share/nas1/liyingying/tools/soft/cogent/Anaconda/anaconda3/envs/anaCogent/lib/python2.7/site-packages/Cogent-2.1-py2.7.egg/EGG-INFO/scripts/reconstruct_contig.py", line 224, in run_Cogent_on_input
    sp.contract_sinks(G, path_d, mermap)
  File "/share/nas1/liyingying/tools/soft/cogent/Anaconda/anaconda3/envs/anaCogent/lib/python2.7/site-packages/Cogent-2.1-py2.7.egg/Cogent/splice_graph.py", line 170, in contract_sinks
    assert path_d[k][-1] == sink and path_d[k][-2] == pred
AssertionError
"""

Could you kindly tell me what might go wrong to cause this? Thanks.

By the way , I have tried add parameters "--nx_cycle_detection -k 60" and it still did not work.

**Comment by Magdoll** [comment] 2018-03-23 23:29
Hi @fantastycrane ,

This usually indicates a pathological case that is causing a bug. 
Would you be able to share the offending case (`in.fa`) to etseng@pacb.com for debugging?

Thanks,
--Liz

**Comment by fantastycrane** [comment] 2018-03-29 07:13
I have sent requested in.fa. Is there any progress?

**Comment by Magdoll** [comment] 2018-03-29 22:05
@fantastycrane ,
I did not receive the email and could not find it in the SPAM either. Please give me an email address and I will request a file dropoff for you to upload.

--Liz

**Comment by fantastycrane** [comment] 2018-03-30 01:23
Here is my email address: fantastycrane@163.com. thanks.

**Comment by Magdoll** [comment] 2018-04-02 14:01
THanks I have received the file. I'm on vacation this week and will look into it when I return to work 4/9.

**Comment by fantastycrane** [comment] 2018-04-16 05:26
Has this bug been fixed?

**Comment by Magdoll** [comment] 2018-04-16 20:40
Hi @fantastycrane ,

This is now fixed in the new version 3.2. The cause of the bug was an edge case where one of your sequences (`c6115/f1p2/4275`) had a polyA tail at the end. While the new version will now run successfully, I would suggest removing the polyA tail since it should have been removed but wasn't. You can use [trim_polyA](https://github.com/bowhan/trim_isoseq_polyA) to remove it or just edit the input sequence.

--Liz

**Comment by fantastycrane** [comment] 2018-04-17 10:23
Thanks.  I'll try update Cogent and trim polyA tail.
Another question, sometimes number of input sequences for reconstruction in one gene family is too large and the reconstruction can not be completed . Could I split the input sequences and perform reconstruction on them separately?

**Comment by Magdoll** [comment] 2018-04-17 16:32
HI @fantastycrane ,

`reconstruct_contigs.py` already automatically splits the input into smaller sizes. The split size is determined in [settings.py `MAX_SPLIT_IN_SIZE`](https://github.com/Magdoll/Cogent/blob/master/Cogent/settings.py#L8) which you are free to change. In fact the input you shared with me was split into two parts. You may have had an old version of Cogent if it did not automatically split input. Let me know how the new install goes.

**Comment by fantastycrane** [comment] 2018-04-19 06:58
Hi @Magdoll ,

The input in my case had been split into several parts as you said. Still, it did not output the final cogent2.renamed.fasta. Here are last few lines in hello.log.

"""
2018-04-10 01:08:37,502 - Cogent.splice_cycle - INFO - K-mer in-seq cycle detection: 452167 in-seq cycle found with max common         sequence analysis showing min: 101, max: 8783, mean: 1273.74606948
2018-04-10 01:58:10,591 - Cogent - INFO - Initial Graph Size: 10002 nodes, 10540 edges
2018-04-10 02:05:29,730 - Cogent - INFO - Post-Reduction Graph Size: 5899 nodes, 6128 edges
2018-04-10 02:05:29,730 - Cogent.process_path - INFO - Number of nodes exceeds 50. Not dealing with pathological case now. Just use the paths!
2018-04-14 14:43:09,150 - Cogent.Utils - WARNING - [BUG] fake_input_path36 is not fully mapped to cogent in GMAP.                 Likely cycle issues. Use itself in output.
2018-04-14 14:43:09,227 - Cogent.Utils - WARNING - [BUG] fake_input_path47 is not fully mapped to cogent in GMAP.                 Likely cycle issues. Use itself in output.
2018-04-14 14:43:09,227 - Cogent.Utils - WARNING - [BUG] fake_input_path48 is not fully mapped to cogent in GMAP.                 Likely cycle issues. Use itself in output.
2018-04-14 14:43:09,254 - Cogent.Utils - WARNING - [BUG] fake_input_path70 is not fully mapped to cogent in GMAP.                 Likely cycle issues. Use itself in output.
2018-04-14 14:43:09,272 - Cogent.Utils - WARNING - [BUG] fake_input_path76 is not fully mapped to cogent in GMAP.                 Likely cycle issues. Use itself in output.
2018-04-14 14:43:09,285 - Cogent.Utils - WARNING - [BUG] fake_input_path93 is not fully mapped to cogent in GMAP.                 Likely cycle issues. Use itself in output.
2018-04-14 14:43:09,299 - Cogent.Utils - WARNING - [BUG] fake_input_path107 is not fully mapped to cogent in GMAP.                 Likely cycle issues. Use itself in output.
2018-04-14 14:43:09,308 - Cogent.Utils - WARNING - [BUG] fake_input_path116 is not fully mapped to cogent in GMAP.                 Likely cycle issues. Use itself in output.
2018-04-14 14:43:09,321 - Cogent.Utils - WARNING - [BUG] fake_input_path142 is not fully mapped to cogent in GMAP.                 Likely cycle issues. Use itself in output.
2018-04-14 14:43:09,335 - Cogent.Utils - WARNING - [BUG] fake_input_path164 is not fully mapped to cogent in GMAP.                 Likely cycle issues. Use itself in output.
2018-04-14 14:43:09,362 - Cogent - INFO - [RUNTIME] for graph construction and reduction: 5461.80457807
2018-04-14 14:43:09,373 - Cogent - INFO - [RUNTIME] for path finding and LP solving: 3.25811696053
2018-04-14 14:43:09,373 - Cogent - INFO - [RUNTIME] for GMAP and post-processing: 391056.373012
2018-04-14 14:43:09,373 - Cogent - INFO - [RUNTIME] Total time in run_Cogent: 396521.435707
2018-04-15 12:09:24,445 - Cogent.Utils - WARNING - [BUG] fake_input_path32 is not fully mapped to cogent in GMAP.                 Likely cycle issues. Use itself in output.
2018-04-15 12:09:24,507 - Cogent.Utils - WARNING - [BUG] fake_input_path46 is not fully mapped to cogent in GMAP.                 Likely cycle issues. Use itself in output.
2018-04-15 12:09:24,507 - Cogent.Utils - WARNING - [BUG] fake_input_path52 is not fully mapped to cogent in GMAP.                 Likely cycle issues. Use itself in output.
2018-04-15 12:09:24,508 - Cogent.Utils - WARNING - [BUG] fake_input_path77 is not fully mapped to cogent in GMAP.                 Likely cycle issues. Use itself in output.
2018-04-15 12:09:24,508 - Cogent.Utils - WARNING - [BUG] fake_input_path127 is not fully mapped to cogent in GMAP.                 Likely cycle issues. Use itself in output.
2018-04-15 12:09:24,508 - Cogent.Utils - WARNING - [BUG] fake_input_path140 is not fully mapped to cogent in GMAP.                 Likely cycle issues. Use itself in output.
2018-04-15 12:09:24,508 - Cogent.Utils - WARNING - [BUG] fake_input_path183 is not fully mapped to cogent in GMAP.                 Likely cycle issues. Use itself in output.
2018-04-15 12:09:24,508 - Cogent.Utils - WARNING - [BUG] fake_input_path198 is not fully mapped to cogent in GMAP.                 Likely cycle issues. Use itself in output.
2018-04-16 21:36:22,266 - Cogent - INFO - [RUNTIME] Total time in run_Cogent: 596925.229742
2018-04-16 21:41:03,777 - Cogent.splice_cycle - INFO - K-mer in-seq cycle detection: 119248 in-seq cycle found with max common         sequence analysis showing min: 101, max: 3198, mean: 739.403721656
2018-04-16 22:15:36,544 - Cogent - INFO - Initial Graph Size: 4953 nodes, 5367 edges
2018-04-16 22:16:19,891 - Cogent - INFO - Post-Reduction Graph Size: 2447 nodes, 2668 edges
2018-04-16 22:16:19,891 - Cogent.process_path - INFO - Number of nodes exceeds 50. Not dealing with pathological case now. Just use the paths!
"""

**Comment by Magdoll** [comment] 2018-04-19 17:48
Hi @fantastycrane , 

That's really weird.  Let's talk through email. Cogent is deterministic so it should be the same results. 

--Liz

**Comment by Magdoll** [comment] 2018-05-07 18:00
Bug is now fixed in Cogent v3.3.

**Closed as completed by Magdoll** 2018-05-07 18:00 UTC
